name: Deploy Club Tag Inspector

on:
  push:
    branches: ["main"]
    paths:
      - "Club Tag Inspector/**"
      - ".github/workflows/pages.yml"

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Upload Club Tag Inspector
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./Club Tag Inspector"

      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4